

# C++ project
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

script:
  - mkdir -p build_runtime
  - cd build_runtime
  - cmake ../compiler/extensions/cpp/runtime/ -GNinja
  - cmake --build .

before_install:
  - eval "${MATRIX_EVAL}"