

# C++ project
language: cpp
dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

script:
  - mkdir -p build_runtime
  - cd build_runtime
  - cmake ../compiler/extensions/cpp/runtime/ -GNinja
  - cmake --build . --config Release
  - ctest -C Release -V --output-on-failure

before_install:
  - eval "${MATRIX_EVAL}"