
# C++ project
language: cpp
dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      compiler:
        - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - ninja-build
      env:
        - CC_COMPILER=gcc-4.9
        - CXX_COMPILER=g++-4.9

script:
  - mkdir -p build_runtime
  - cd build_runtime
  - export CC=${CC_COMPILER}
  - export CXX=${CXX_COMPILER}
  - cmake -DZSERIO_RUNTIME_INCLUDE_INSPECTOR ../compiler/extensions/cpp/runtime/ -GNinja
  - cmake --build . --config Release
  - ctest -C Release -V --output-on-failure